apiVersion: apps/v1
kind: Deployment
metadata:
  name: door-service-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: door-service-gateway
  template:
    metadata:
      labels:
        app: door-service-gateway
    spec:
      containers:
      - name: door-service-gateway
        image: 767397708304.dkr.ecr.eu-west-1.amazonaws.com/doorapp/gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
---
apiVersion: v1
kind: Service
metadata: door-service-gateway
spec:
  selector:
    app: door-service-gateway
  ports:
  name: 
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer


