name: Build and Deploy to EKS

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out code from the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Run Unit Tests
      - name: Run Unit Tests
        run: |
          dotnet test --filter TestCategory=Unit
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          # AWS_REGION: eu-west-1

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 767397708304.dkr.ecr.eu-west-1.amazonaws.com

      # Build and push Docker image to Amazon ECR
      - name: Build and push Docker image
        run: |
          docker build -t 767397708304.dkr.ecr.eu-west-1.amazonaws.com/doorservice/gateway:latest .
          docker push 767397708304.dkr.ecr.eu-west-1.amazonaws.com/doorservice/gateway:latest

      # Set up kubeconfig for EKS
      - name: Set up Kubeconfig for EKS
        run: |
          aws eks --region eu-west-1 update-kubeconfig --name doorapp

      - name: apply kubernates yaml
        run: |
          kubectl apply -f kubdeployment.yml

      # Update Kubernetes deployment
      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/door-service-gateway door-service-gateway=767397708304.dkr.ecr.eu-west-1.amazonaws.com/doorservice/gateway:latest
