name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Unit Testing Step
    - name: Run Unit Tests
      run: |
        # Example command for running unit tests with dotnet; modify for your specific test runner
        dotnet test --filter TestCategory=Unit
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    # Integration Testing Step
    - name: Run Integration Tests
      run: |
        # Example command for running integration tests with dotnet; modify for your specific test runner
        dotnet test --filter TestCategory=Integration
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    # Build Docker image
    - name: Log in to Amazon ECR
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: <region>
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin <account_id>.dkr.ecr.$AWS_REGION.amazonaws.com

    - name: Build and push Docker image
      run: |
        docker build -t <account_id>.dkr.ecr.<region>.amazonaws.com/your_service_name:latest .
        docker push <account_id>.dkr.ecr.<region>.amazonaws.com/your_service_name:latest

    # Update Kubernetes deployment
    - name: Update Kubernetes deployment
      run: |
        kubectl set image deployment/your-service your-service=<account_id>.dkr.ecr.<region>.amazonaws.com/your_service_name:latest
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
